language: scala
scala:
  - 2.11.6
jdk:
  - oraclejdk8
services:
  - riak
before_script:
  - riak-admin bucket-type create journal '{"props":{"datatype":"map"}}'
  - riak-admin bucket-type activate journal
  - riak-admin bucket-type create journal-seqnrs '{"props":{"datatype":"set"}}'
  - riak-admin bucket-type activate journal-seqnrs

