language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
services:
  - riak
before_script:
  - sudo riak-admin bucket-type create journal '{"props":{"datatype":"map"}}'
  - sudo riak-admin bucket-type activate journal
  - sudo riak-admin bucket-type create journal-seqnrs '{"props":{"datatype":"set"}}'
  - sudo riak-admin bucket-type activate journal-seqnrs
