language: scala
scala:
   - 2.10.4
   - 2.11.4
jdk:
  - oraclejdk7
services:
  - riak
before_script: 
  - sudo riak-admin bucket-type create journal '{"props": {}}'
  - sudo riak-admin bucket-type activate journal
  - sudo riak-admin bucket-type create journal-seqnrs '{"props":{"datatype":"set"}}'
  - sudo riak-admin bucket-type activate journal-seqnrs

